### ISSUE TITLE
status=0

### ISSUE THREAD

**Issue by dimsua** [olegfedoseev/pinba-server#3]
Приветствую
В основной массе случаев status=0, очень редко 200 
В логах 200 ответы
Это нормально для pinba или что-то где-то не так?
2015/03/12 18:38:30 [Decoder] Data: [request  1426174710 0.383285 1 0.357945 host=server.name server=domain1.ru script=/index.php status=200]
2015/03/12 18:38:31 [Decoder] Decoded 1 (33.932us), sent 1
2015/03/12 18:38:31 [Listener] Got 3 packets for 18:38:31
2015/03/12 18:38:31 [Decoder] Data: [request  1426174711 0.014785 1 0.007998 host=server.name server=domain2.ru script=/webim/operator/update.php status=0]
2015/03/12 18:38:31 [Decoder] Data: [request  1426174711 0.461625 1 0.413937 host=server.name server=domain3.ru script=/the-cabinet-domain3-therapy/for-patients/index.php status=0]
2015/03/12 18:38:31 [Decoder] Data: [request  1426174711 0.073268 1 0.068989 host=server.name server=domain4.ru script=/index.php status=0]
2015/03/12 18:38:32 [Decoder] Decoded 3 (54.246us), sent 3
2015/03/12 18:38:32 [Listener] Got 1 packets for 18:38:32
2015/03/12 18:38:32 [Decoder] Data: [request  1426174712 0.063098 1 0.051992 host=server.name server=domain5.ru script=/index.php status=0]
2015/03/12 18:38:33 [Decoder] Decoded 1 (34.113us), sent 1
2015/03/12 18:38:33 [Listener] Got 4 packets for 18:38:33
2015/03/12 18:38:33 [Decoder] Data: [request  1426174713 0.056601 1 0.052992 host=server.name server=domain5.ru script=/index.php status=0]
2015/03/12 18:38:33 [Decoder] Data: [request  1426174713 0.016567 1 0.011998 host=server.name server=domain2.ru script=/webim/operator/update.php status=0]
2015/03/12 18:38:33 [Decoder] Data: [request  1426174713 0.065670 1 0.060992 host=server.name server=domain5.ru script=/index.php status=0]
2015/03/12 18:38:33 [Decoder] Data: [request  1426174713 0.083932 1 0.069989 host=server.name server=domain5.ru script=/index.php status=0]
2015/03/12 18:38:34 [Decoder] Decoded 4 (56.22us), sent 4
2015/03/12 18:38:34 [Listener] Got 4 packets for 18:38:34
2015/03/12 18:38:34 [Decoder] Data: [request  1426174714 0.057015 1 0.050993 host=server.name server=domain5.ru script=/index.php status=0]
2015/03/12 18:38:34 [Decoder] Data: [request  1426174714 3.159041 1 0.082987 host=server.name server=www.domain6.ru script=/pay.php status=0]
2015/03/12 18:38:34 [Decoder] Data: [request  1426174714 0.061835 1 0.055991 host=server.name server=domain5.ru script=/index.php status=0]
2015/03/12 18:38:34 [Decoder] Data: [request  1426174714 0.065791 1 0.055992 host=server.name server=domain5.ru script=/index.php status=0]

**Comment by olegfedoseev** [comment]
Я такое поведение видел, но не так массово.
Какой версии экстеншен пинбы? Запросы с статусом 0 отрабатывают корректно?

Я бы для начала добавил в конец запроса (например через shutdown function) вывод pinba_get_info(), это покажет что экстеншен собрал и что он будет отправлять на сервер.

**Comment by dimsua** [comment]
Оказалось все дело в sapi litespeed (мы используем litespeed в качестве веб-сервера), который по умолчанию выставляет код 0, если приложение не установило другой код, поменяли код в lsapi, теперь все нормально.
